version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: server_infor_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: serverindormation_db
      MYSQL_USER: serinformation
      MYSQL_PASSWORD: 123456
    ports:
      - "3388:3306"

volumes:
  db_data: